spring:
  data:
    mongodb:
      uri: mongodb+srv://iobuilders:78yfNWjC8TnwG@fun-wallet-mongodb.iech7.mongodb.net/funWalletDb?retryWrites=true&w=majority

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG